[[redirects]]
    from="https://www.lehtinen.xyz/*"
    to="https://op.lehtinen.xyz/:splat"
    status= 301
    force=true
[[redirects]]
    from="https://lehtinen.xyz/*"
    to="https://op.lehtinen.xyz/:splat"
    status= 301
    force=true
[[redirects]]
    from="/*"
    to"/404/"
    status=301